service: sdp-fetch-opened

provider:
  name: google
  runtime: python37
  region: us-central1
  project: ceservicedeskstats
  credentials: ~/.gcloud/gcloud.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - config.json.example
    - config.json.gpg
    - stats-opened/**

functions:
  fetch-opened:
    handler: fetchopened
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/FetchOpened'

resources:
  resources:
    - type: storage.v1.bucket
      name: ceservicedeskstats
