service: fetch-opened

provider:
  name: google
  runtime: python37
  region: us-central1
  project: ceservicedeskstats
  credentials: ~/.gcloud/ceservicedeskstats.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - config.json.example
    - stats-opened/**

functions:
  fetch-stats:
    handler: fetchOpened
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/FetchOpened'
