service: sdp-import-stats

provider:
  name: google
  runtime: python37
  region: us-central1
  project: ceservicedeskstats
  credentials: ~/.gcloud/gcloud.json

plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - config.json.example
    - config.json.gpg

functions:
  fetch-stats:
    handler: importstats
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/ceservicedeskstats'

resources:
  resources:
    - type: storage.v1.bucket
      name: ceservicedeskstats
