service: fetch-closed

provider:
  name: google
  runtime: python37
  region: us-central1
  project: ceservicedeskstats
  credentials: ~/.gcloud/gcloud.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - config.json.example
    - config.json.gpg
    - stats-closed/**

functions:
  fetch-stats:
    handler: fetchClosed
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/FetchClosed'

resources:
  resources:
    - type: storage.v1.bucket
      name: ceservicedeskstats